---
# tasks file for zookeeper

# Configure environment
- name: Create Zookeeper Group
  group:
    name: "{{zookeeper.group}}"

- name: Create Zookeeper User
  user:
    name: "{{zookeeper.user}}"
    comment: "Zookeeper User"
    system: yes
    group: "{{zookeeper.group}}"



