all:
  vars:
    ansible_connection: ssh
    ansible_user: ansible
    ansible_become: true
    ansible_ssh_private_key_file: /home/ansible/.ssh/id_rsa

    # Random shifts for retrying failed ops like downloading
    retry_stagger: 5

    # Local
    ansible_log_dir: "{{ playbook_dir }}/log"
    downloads_dir: "{{ playbook_dir }}/downloads"
    conf_dir: "{{ playbook_dir }}/conf"
    deploy_dir: /opt
    package_dir: "{{ deploy_dir }}/package"
    
    java_version: "8u241"
    java_download_dir: "/opt/downloads"
    java_download_url: "https://download.oracle.com/otn/java/jdk/8u241-b07/1f5b5a70bf22433b84d0e960903adac8/jdk-{{ java_version }}-linux-i586.tar.gz"
    java_symlink_to: "/usr/local/java"

zookeeper_servers:
    hosts:
      172.31.32.90:
        client_port: 2181      
    vars:
      ansible_python_interpreter: /usr/bin/python3

kafka_servers:
    hosts:
      172.31.32.90:
        id: 1
        kafka_port: 9092

    vars:
      ansible_python_interpreter: /usr/bin/python3








