all:
  vars:
    ansible_connection: ssh
    ansible_user: ansible
    ansible_become: true
    ansible_ssh_private_key_file: /home/ansible/.ssh/id_rsa

zookeeper:
    hosts:
      172.31.36.115:








